import React from "react"
import Head from "next/head"
import type { NextPage } from "next"

const Home: NextPage = () => {
  console.log("from index page")

  return (
    <React.Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </React.Fragment>
  )
}

export default Home
