import Chat from "./chat"
import React from "react"
import Head from "next/head"
import Image from "next/image"
import Router from "next/router"
import type { NextPage } from "next"
import styles from "../styles/Home.module.css"

type FormEvent = React.FormEvent<HTMLFormElement>
type InputEvent = React.ChangeEvent<HTMLInputElement>

const Home: NextPage = () => {
  const [txt, setTxt] = React.useState("")
  const [user, setUser] = React.useState<string | null>(null)
  const handleChange = (e: InputEvent) => setTxt(e.target.value)

  const handleSubmit = (e: FormEvent) => {
    e.preventDefault()
    setUser(txt)
  }

  return user && user.length ? (
    <Chat user={user} />
  ) : (
    <React.Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p>Please give us a name to join the chat with</p>
      <form onSubmit={handleSubmit}>
        <input name="txt" value={txt} onChange={handleChange} />
        <button type="submit">Send</button>
      </form>
    </React.Fragment>
  )
}

export default Home
